platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Required: load Flutter pod helpers
require File.expand_path(File.join('..', 'Flutter', 'pods_support', 'flutter_tools.rb'), __dir__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
